production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: <%= ENV['SMTP_ADDRESS'] %>
      port: <%= ENV['SMTP_PORT'] %>
      domain: <%= ENV['SMTP_DOMAIN'] %>
      authentication: <%= ENV['SMTP_AUTHENTICATION'] %>
      user_name: <%= ENV['SMTP_USER_NAME'] %>
      password: <%= ENV['SMTP_PASSWORD'] %>
      enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] %>